# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/RV32I_WSC/RV32I_WSC.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV32I_WSC || ORIG_REF_NAME==RV32I_WSC} -quiet] -quiet

# IP: bd/RV32I_WSC/ip/RV32I_WSC_Instruction_Fetch_0_0/RV32I_WSC_Instruction_Fetch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV32I_WSC_Instruction_Fetch_0_0 || ORIG_REF_NAME==RV32I_WSC_Instruction_Fetch_0_0} -quiet] -quiet

# IP: bd/RV32I_WSC/ip/RV32I_WSC_Instruction_Decode_0_0/RV32I_WSC_Instruction_Decode_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV32I_WSC_Instruction_Decode_0_0 || ORIG_REF_NAME==RV32I_WSC_Instruction_Decode_0_0} -quiet] -quiet

# IP: bd/RV32I_WSC/ip/RV32I_WSC_reg_IFID_0_0/RV32I_WSC_reg_IFID_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV32I_WSC_reg_IFID_0_0 || ORIG_REF_NAME==RV32I_WSC_reg_IFID_0_0} -quiet] -quiet

# IP: bd/RV32I_WSC/ip/RV32I_WSC_reg_IDEX_0_0/RV32I_WSC_reg_IDEX_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV32I_WSC_reg_IDEX_0_0 || ORIG_REF_NAME==RV32I_WSC_reg_IDEX_0_0} -quiet] -quiet

# IP: bd/RV32I_WSC/ip/RV32I_WSC_Execution_0_0/RV32I_WSC_Execution_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV32I_WSC_Execution_0_0 || ORIG_REF_NAME==RV32I_WSC_Execution_0_0} -quiet] -quiet

# IP: bd/RV32I_WSC/ip/RV32I_WSC_reg_EXMEM_0_0/RV32I_WSC_reg_EXMEM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV32I_WSC_reg_EXMEM_0_0 || ORIG_REF_NAME==RV32I_WSC_reg_EXMEM_0_0} -quiet] -quiet

# IP: bd/RV32I_WSC/ip/RV32I_WSC_Memory_0_0/RV32I_WSC_Memory_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV32I_WSC_Memory_0_0 || ORIG_REF_NAME==RV32I_WSC_Memory_0_0} -quiet] -quiet

# IP: bd/RV32I_WSC/ip/RV32I_WSC_reg_MEMWB_0_1/RV32I_WSC_reg_MEMWB_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV32I_WSC_reg_MEMWB_0_1 || ORIG_REF_NAME==RV32I_WSC_reg_MEMWB_0_1} -quiet] -quiet

# IP: bd/RV32I_WSC/ip/RV32I_WSC_Write_back_0_0/RV32I_WSC_Write_back_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV32I_WSC_Write_back_0_0 || ORIG_REF_NAME==RV32I_WSC_Write_back_0_0} -quiet] -quiet

# IP: bd/RV32I_WSC/ip/RV32I_WSC_Hazard_Processing_0_1/RV32I_WSC_Hazard_Processing_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV32I_WSC_Hazard_Processing_0_1 || ORIG_REF_NAME==RV32I_WSC_Hazard_Processing_0_1} -quiet] -quiet

# IP: bd/RV32I_WSC/ip/RV32I_WSC_Fowarding_Unit_0_0/RV32I_WSC_Fowarding_Unit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RV32I_WSC_Fowarding_Unit_0_0 || ORIG_REF_NAME==RV32I_WSC_Fowarding_Unit_0_0} -quiet] -quiet

# XDC: c:/FPGA_project/RV32I_WSC/RV32I_WSC.gen/sources_1/bd/RV32I_WSC/RV32I_WSC_ooc.xdc
